### PR TITLE
Add copy button to editors

### PR DESCRIPTION
**Pull request by steven1046**

### CODE REVIEW

**Comment by steven1046** [comment]
I'm moving the error pane code out of the micro-profile-config-callback.js file so it can be used for the copy button as well.

**Comment by steven1046** [comment]
image

This is what will be shown when the copy fails.

**Comment by chirp1** [comment]
How about if you change the wording on the image to "The contents failed to copy to the clipboard. Copy the contents manually."?

**Comment by chirp1** [comment]
I reviewed the updates . They look good.

**Pull request merged**
